FC = <FC>

FFLAGS = <FRTFLAGS> -I<HDF5_INCLUDE_DIR>

OBJS = psi_io.o conflow.o

LDFLAGS = -L<HDF5_LIB_DIR> <HDF5_LIB_FLAGS>

all: $(OBJS)
	$(FC) $(FFLAGS) $(OBJS) $(LDFLAGS) -o conflow
	rm *.mod *.o 2>/dev/null

install:
	mv conflow ../bin/

clean:
	rm -f conflow 2>/dev/null
	rm -f *.mod *.o 2>/dev/null

psi_io.o: psi_io.f90
	$(FC) $(FFLAGS) -c psi_io.f90

conflow.o : conflow.f90
	$(FC) $(FFLAGS) -c conflow.f90
